### ISSUE TITLE
Roadmap 🏳

### ISSUE THREAD

**Issue by Yakiyo** [Yakiyo/Yume-Bot#18]
This issue tracks the roadmap for what's to come in the future.

## Version 2 
Base issue - #19 
Base pr - #9 
- [x] Move to slash commands
- [x] Database feature  #5
- [ ] Add chat rankings, user profiles and xp 
- [ ] Graphical profile command
- [ ] Bi Directional Modmail #17
- [ ] Permission Handler #4 
- [ ] Button Roles #11 
- [ ] Mod Logs #14 
- [ ] Server Logs #14 
- [ ] Context Menus

Long Term Features (Probably to be implemented after stable v2)
- [ ] Discord.js v14 #7 
- [ ] Character Game #13 
- [ ] Typescript rewrite #6 
- [ ] Anti Raid measures
